name: GitHub Actions Demo
on: [push]
jobs:
    test:
        runs-on: ubuntu-18.04
        steps:
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Echo
              run: echo ${{ steps.get_version.outputs.VERSION }}
